# Generated by Django 3.2.3 on 2021-05-26 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contect_form',
            fields=[
                ('contect_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(default='', max_length=80)),
                ('c_email', models.CharField(default='', max_length=80)),
                ('c_phone', models.CharField(default='', max_length=80)),
                ('c_descri', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='order_update',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_items_json', models.CharField(max_length=5000)),
                ('amount', models.IntegerField(default=0)),
                ('order_name', models.CharField(max_length=90)),
                ('order_email', models.CharField(max_length=111)),
                ('order_address', models.CharField(max_length=111)),
                ('order_city', models.CharField(max_length=111)),
                ('order_state', models.CharField(max_length=111)),
                ('order_zip_code', models.CharField(max_length=111)),
                ('order_phone', models.CharField(default='', max_length=111)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('sub_category', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('product_descri', models.TextField(max_length=800)),
                ('product_rating', models.CharField(default='5', max_length=5)),
                ('product_brand', models.CharField(default='unKnown', max_length=50)),
                ('product_status', models.CharField(default='Avaliable', max_length=50)),
                ('product_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='A_shop/images')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title_text', models.TextField(blank=True, max_length=50)),
                ('review_text', models.TextField(blank=True, max_length=300)),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, '1 - Trash'), (2, '2 - Normal'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Perfect')])),
                ('likes', models.PositiveIntegerField(default=0)),
                ('unlikes', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('review_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
